version: '3'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  tests:
    build: . 
    depends_on:
      - chrome
    volumes:
      - ./allure-results:/app/allure-results
